# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "waratek/demo"
  config.vm.hostname = "sqlmap.localdomain"

  config.vm.network "forwarded_port", guest: 80, host: 8000
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.synced_folder "../../", "/vagrant"

  # VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.name = "sqlmap test"
    vb.customize ["modifyvm", :id, "--biosbootmenu", "disabled"]
    vb.customize ["modifyvm", :id, "--bioslogodisplaytime", "0"]
    vb.customize ["modifyvm", :id, "--bioslogofadein", "off"]
    vb.customize ["modifyvm", :id, "--bioslogofadeout", "off"]
    vb.customize ["modifyvm", :id, "--cpus", "4"]
    vb.customize ["modifyvm", :id, "--ioapic", "on"]
    vb.customize ["modifyvm", :id, "--memory", "1536"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
  end

  # VMware Fusion
  config.vm.provider "vmware_fusion" do |vmf|
    vmf.vmx["memsize"] = "1536"
    vmf.vmx["numvcpus"] = "4"
  end

  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "../../puppet/manifests"
    puppet.manifest_file = "site.pp"
    puppet.module_path = "../../puppet/modules"
    #puppet.options = "--verbose --debug"
    puppet.facter = {
      "vagrantuser"  => "vagrant",
      "waratek_demo" => "jaf_demo_sqlmap"
    }
  end

end
