= Waratek Demos

== Requirements

* link:http://www.vagrantup.com/[Vagrant]
* link:http://www.virtualbox.org/[VirtualBox]

== Running

After downloading and installing Vagrant and Virtualbox:

----
$ vagrant up
$ vagrant ssh
----

and when you're done...

----
$ vagrant destroy
----

=== AWS

The Vagrant configuration also supports deployment to Amazon EC2.  You'll need to install the AWS provider plugin before use:

----
$ vagrant plugin install vagrant-aws
----

AWS configuration is exposed via environment variables.  They can be set as follows prior to running vagrant e.g.:

----
$ export AWS_ACCESS_KEY="YOUR ACCESS KEY"
$ export AWS_SECRET_KEY="YOUR AWS SECRET KEY"
$ export AWS_KEYPAIR_NAME="default"
$ export AWS_REGION="eu-west-1"
$ export AWS_PRIVATE_KEY_PATH="/path/to/private_key.pem"
$ vagrant up --provider=aws
...
----

Refer to the link:https://github.com/mitchellh/vagrant-aws[vagrant-aws plugin repository] for further information

== License

Please refer to the link:LICENSE.txt[Waratek Software License Agreement] for further information on licensing terms.

The Waratek CloudVM software will be installed for a time limited evaluation period of 30 days and will allow the use of four Java Virtual Containers (JVCs).  To obtain an extended evaluation license, please contact licensing@waratek.com.

If you have received a license key file from Waratek, you can save it to the same directory as the Vagrantfile and it will be installed when the box is provisioned.  Alternately, you can copy the _LICENSE_KEY_ file directly to _/var/lib/javad/_ on the box.
