# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--biosbootmenu", "disabled"]
    v.customize ["modifyvm", :id, "--bioslogodisplaytime", "0"]
    v.customize ["modifyvm", :id, "--bioslogofadein", "off"]
    v.customize ["modifyvm", :id, "--bioslogofadeout", "off"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
  end

  # demo1
  config.vm.define "demo1", primary: true do |demo1|
    demo1.vm.box = "waratek/centos6-x86_64"
    demo1.vm.box_version = "~> 1.0"
    demo1.vm.hostname = "demo1.example.com"

    demo1.vm.network "private_network", ip: "172.21.21.21"
    demo1.vm.network "public_network", ip: "10.1.2.101", :netmask => "255.255.0.0", bridge: "eth0"

    demo1.vm.synced_folder "../../synced_folder", "/synced_folder"
    demo1.vm.synced_folder "../../puppet/hieradata", "/tmp/hieradata"
    
    demo1.vm.provider "virtualbox" do |v|
      v.name = "Waratek_demo1"
      v.cpus = 2
      v.memory = 2048
    end

    demo1.vm.provision "puppet", run: "always" do |puppet|
      puppet.manifests_path = "../../puppet/manifests"
      puppet.manifest_file = "site.pp"
      puppet.module_path = "../../puppet/modules"
      puppet.hiera_config_path = "../../puppet/hiera.yaml"
      #puppet.options = "--verbose --debug"
      puppet.facter = {
        "role"        => "security_demo_centos",
        "vagrant"     => "true",
        "vagrantuser" => "vagrant",
      }
    end
  end

  # demo2
  config.vm.define "demo2" do |demo2|
    demo2.vm.box = "waratek/centos6-x86_64"
    demo2.vm.box_version = "~> 1.0"
    demo2.vm.hostname = "demo2.example.com"

    demo2.vm.network "private_network", ip: "172.21.21.22"
    demo2.vm.network "public_network", ip: "10.1.2.102", :netmask => "255.255.0.0", bridge: "eth0"

    demo2.vm.synced_folder "../../synced_folder", "/synced_folder"
    demo2.vm.synced_folder "../../puppet/hieradata", "/tmp/hieradata"
    
    demo2.vm.provider "virtualbox" do |v|
      v.name = "Waratek_demo2"
      v.cpus = 2
      v.memory = 2048
    end

    demo2.vm.provision "puppet", run: "always" do |puppet|
      puppet.manifests_path = "../../puppet/manifests"
      puppet.manifest_file = "site.pp"
      puppet.module_path = "../../puppet/modules"
      puppet.hiera_config_path = "../../puppet/hiera.yaml"
      #puppet.options = "--verbose --debug"
      puppet.facter = {
        "role"        => "security_demo_centos",
        "vagrant"     => "true",
        "vagrantuser" => "vagrant",
      }
    end
  end

  # Kali
  config.vm.define "kali" do |kali|
    kali.vm.box = "waratek/kali-mini"
    kali.vm.box_version = "~> 1.0"
    kali.vm.guest = "debian"
    kali.vm.hostname = "kali.example.com"
    kali.ssh.username = "root"

    kali.vm.network "private_network", ip: "172.21.21.30"
    kali.vm.network "public_network", ip: "10.1.2.130", :netmask => "255.255.0.0", bridge: "eth0"

    kali.vm.synced_folder "../../synced_folder", "/synced_folder"
    kali.vm.synced_folder "../../puppet/hieradata", "/tmp/hieradata"
    
    kali.vm.provider "virtualbox" do |v|
      v.name = "Waratek_kali"
      v.cpus = 2
      v.memory = 2048
    end

    kali.vm.provision "puppet", run: "always" do |puppet|
      puppet.manifests_path = "../../puppet/manifests"
      puppet.manifest_file = "site.pp"
      puppet.module_path = "../../puppet/modules"
      puppet.hiera_config_path = "../../puppet/hiera.yaml"
      #puppet.options = "--verbose --debug"
      puppet.facter = {
        "role"        => "security_demo_kali"
      }
    end
  end

  # Monitor
  config.vm.define "monitor" do |monitor|
    monitor.vm.box = "waratek/centos6-x86_64"
    monitor.vm.box_version = "~> 1.0"
    monitor.vm.hostname = "monitor.example.com"

    monitor.vm.network "private_network", ip: "172.21.21.40"
    monitor.vm.network "public_network", ip: "10.1.2.140", :netmask => "255.255.0.0", bridge: "eth0"

    monitor.vm.synced_folder "../../synced_folder", "/synced_folder"
    monitor.vm.synced_folder "../../puppet/hieradata", "/tmp/hieradata"
    
    monitor.vm.provider "virtualbox" do |v|
      v.name = "Waratek_monitor"
      v.cpus = 2
      v.memory = 2048
    end

    monitor.vm.provision "puppet", run: "always" do |puppet|
      puppet.manifests_path = "../../puppet/manifests"
      puppet.manifest_file = "site.pp"
      puppet.module_path = "../../puppet/modules"
      puppet.hiera_config_path = "../../puppet/hiera.yaml"
      #puppet.options = "--verbose --debug"
      puppet.facter = {
        "role"        => "security_demo_monitor"
      }
    end
  end

end
