# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--biosbootmenu", "disabled"]
    v.customize ["modifyvm", :id, "--bioslogodisplaytime", "0"]
    v.customize ["modifyvm", :id, "--bioslogofadein", "off"]
    v.customize ["modifyvm", :id, "--bioslogofadeout", "off"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
  end

  # CentOS
  config.vm.define "centos", primary: true do |centos|
    centos.vm.box = "waratek/centos6-x86_64"
    centos.vm.hostname = "centos.brix.waratek.com"

    centos.vm.network "private_network", ip: "172.21.21.21"
    centos.vm.network "public_network", ip: "10.1.2.101", :netmask => "255.255.0.0"
    centos.vm.network "forwarded_port", guest: 6060, host: 6060 # Tomcat 6
    centos.vm.network "forwarded_port", guest: 8080, host: 8080 # Tomcat 7
    centos.vm.network "forwarded_port", guest: 9090, host: 9090 # httpd

    centos.vm.synced_folder "../../synced_folder", "/synced_folder"
    centos.vm.synced_folder "../../puppet/hieradata", "/tmp/hieradata"
    
    centos.vm.provider "virtualbox" do |v|
      v.name = "Waratek_CentOS"
      v.cpus = 2
      v.memory = 2048
    end

    centos.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "../../puppet/manifests"
      puppet.manifest_file = "site.pp"
      puppet.module_path = "../../puppet/modules"
      puppet.hiera_config_path = "../../puppet/hiera.yaml"
      #puppet.options = "--verbose --debug"
      puppet.facter = {
        "role"        => "security_demo_centos",
        "vagrant"     => "true",
        "vagrantuser" => "vagrant",
      }
    end
  end

  # Kali
  config.vm.define "kali" do |kali|
    kali.vm.box = "waratek/kali-mini"
    kali.vm.guest = "debian"
    kali.vm.hostname = "kali.brix.waratek.com"
    kali.ssh.username = "root"

    kali.vm.network "private_network", ip: "172.21.21.22"
    kali.vm.network "public_network", ip: "10.1.2.102", :netmask => "255.255.0.0"

    kali.vm.synced_folder "../../synced_folder", "/synced_folder"
    kali.vm.synced_folder "../../puppet/hieradata", "/tmp/hieradata"
    
    kali.vm.provider "virtualbox" do |v|
      v.name = "Waratek_Kali"
      v.cpus = 2
      v.memory = 2048
    end

    kali.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "../../puppet/manifests"
      puppet.manifest_file = "site.pp"
      puppet.module_path = "../../puppet/modules"
      puppet.hiera_config_path = "../../puppet/hiera.yaml"
      #puppet.options = "--verbose --debug"
      puppet.facter = {
        "role"        => "security_demo_kali"
      }
    end
  end

  # Monitor
  config.vm.define "monitor" do |monitor|
    monitor.vm.box = "waratek/centos6-x86_64"
    monitor.vm.hostname = "monitor.brix.waratek.com"

    monitor.vm.network "private_network", ip: "172.21.21.23"
    monitor.vm.network "public_network", ip: "10.1.2.103", :netmask => "255.255.0.0"
    monitor.vm.network "forwarded_port", guest: 8000, host: 8000 # Splunk

    monitor.vm.synced_folder "../../synced_folder", "/synced_folder"
    monitor.vm.synced_folder "../../puppet/hieradata", "/tmp/hieradata"
    
    monitor.vm.provider "virtualbox" do |v|
      v.name = "Waratek_monitor"
      v.cpus = 2
      v.memory = 2048
    end

    monitor.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "../../puppet/manifests"
      puppet.manifest_file = "site.pp"
      puppet.module_path = "../../puppet/modules"
      puppet.hiera_config_path = "../../puppet/hiera.yaml"
      #puppet.options = "--verbose --debug"
      puppet.facter = {
        "role"        => "security_demo_monitor"
      }
    end
  end

end
